from typing import List
from pydantic import BaseModel, Field

class CaseEvidencePlan(BaseModel):
    """
    Plan generated by the Case Evidence Planner to identify which structured
    fields from the CanonicalCase are relevant for investigation.
    """
    relevant_entities: List[str] = Field(
        ..., description="List of entity types to check (e.g. 'transaction', 'order', 'delivery')"
    )
    relevant_fields: List[str] = Field(
        ..., description="Specific fields to fetch, in format 'entity.field_name' (e.g. 'delivery.status')"
    )
    evidence_categories: List[str] = Field(
        ..., description="Categorization of the evidence (e.g. 'payment', 'fulfillment', 'delivery')"
    )
    rationale: str = Field(
        ..., description="Explanation of why these fields are required for the dispute allegation"
    )

class PolicyEvidencePlan(BaseModel):
    """
    Plan generated by the Policy Evidence Planner to identify which rules
    to search for in the policy corpus.
    """
    search_queries: List[str] = Field(
        ..., description="List of natural language queries for vector and BM25 search"
    )
    policy_topics: List[str] = Field(
        ..., description="Key topics to filter or categorize the search (e.g. 'evidence requirements')"
    )
    required_policy_context: List[str] = Field(
        ..., description="What specific context is being looked for in the policies"
    )
