"""Initial Phase 1 Schema

Revision ID: 54259c35c864
Revises: 
Create Date: 2026-08-28 16:08:05.754832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '54259c35c864'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.create_table('customers',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('customer_city', sa.String(), nullable=False),
    sa.Column('customer_state', sa.String(), nullable=False),
    sa.Column('customer_zip_code_prefix', sa.String(), nullable=False),
    sa.Column('customer_region', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('customer_email', sa.String(), nullable=False),
    sa.Column('customer_phone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('merchants',
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('seller_city', sa.String(), nullable=False),
    sa.Column('seller_state', sa.String(), nullable=False),
    sa.Column('seller_zip_code_prefix', sa.String(), nullable=False),
    sa.Column('merchant_region', sa.String(), nullable=False),
    sa.Column('merchant_name', sa.String(), nullable=False),
    sa.Column('merchant_email', sa.String(), nullable=False),
    sa.Column('merchant_phone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('order_status', sa.String(), nullable=False),
    sa.Column('order_purchase_timestamp', sa.DateTime(), nullable=True),
    sa.Column('order_approved_at', sa.DateTime(), nullable=True),
    sa.Column('order_delivered_carrier_date', sa.DateTime(), nullable=True),
    sa.Column('order_delivered_customer_date', sa.DateTime(), nullable=True),
    sa.Column('order_estimated_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_delay_days', sa.Float(), nullable=True),
    sa.Column('purchase_to_delivery_days', sa.Float(), nullable=True),
    sa.Column('derived_delivery_state', sa.String(), nullable=False),
    sa.Column('order_channel', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('policy_documents',
    sa.Column('policy_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_table('system_metadata',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('payment_type', sa.String(), nullable=False),
    sa.Column('payment_installments', sa.Integer(), nullable=False),
    sa.Column('payment_value', sa.Float(), nullable=False),
    sa.Column('payment_total', sa.Float(), nullable=False),
    sa.Column('payment_count', sa.Integer(), nullable=False),
    sa.Column('transaction_status', sa.String(), nullable=False),
    sa.Column('authorization_status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('deliveries',
    sa.Column('delivery_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('order_delivered_carrier_date', sa.DateTime(), nullable=True),
    sa.Column('order_delivered_customer_date', sa.DateTime(), nullable=True),
    sa.Column('order_estimated_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_delay_days', sa.Float(), nullable=True),
    sa.Column('delivery_state', sa.String(), nullable=False),
    sa.Column('tracking_id', sa.String(), nullable=False),
    sa.Column('carrier_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('delivery_id')
    )
    op.create_table('disputes',
    sa.Column('dispute_id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('canonical_order_id', sa.String(), nullable=False),
    sa.Column('dispute_type', sa.String(), nullable=False),
    sa.Column('dispute_reason', sa.String(), nullable=False),
    sa.Column('dispute_amount', sa.Float(), nullable=False),
    sa.Column('dispute_opened_at', sa.DateTime(), nullable=False),
    sa.Column('dispute_status', sa.String(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('dispute_id')
    )
    op.create_table('policy_parent_chunks',
    sa.Column('parent_chunk_id', sa.String(), nullable=False),
    sa.Column('policy_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policy_documents.policy_id'], ),
    sa.PrimaryKeyConstraint('parent_chunk_id')
    )
    op.create_table('policy_child_chunks',
    sa.Column('child_chunk_id', sa.String(), nullable=False),
    sa.Column('parent_chunk_id', sa.String(), nullable=False),
    sa.Column('policy_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.ForeignKeyConstraint(['parent_chunk_id'], ['policy_parent_chunks.parent_chunk_id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policy_documents.policy_id'], ),
    sa.PrimaryKeyConstraint('child_chunk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policy_child_chunks')
    op.drop_table('policy_parent_chunks')
    op.drop_table('disputes')
    op.drop_table('deliveries')
    op.drop_table('transactions')
    op.drop_table('system_metadata')
    op.drop_table('policy_documents')
    op.drop_table('orders')
    op.drop_table('merchants')
    op.drop_table('customers')
    # ### end Alembic commands ###
